version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.7.2
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

jobs:
  test_regression_model:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv      
      - run:
          name: Install requirements
          command: |
            . venv/bin/activate
            pip install -r src/requirements.txt
      - run:
          name: Train model
          command: |
            . venv/bin/activate
            PYTHONPATH=./src python3 src/regression_model/train_pipeline.py
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            py.test -vv src/tests

  test_ml_api:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - py-deps-{{ checksum "ml_api/requirements.txt" }}
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r ml_api/requirements.txt
            py.test -vv packages/ml_api/tests -m "not differential"
      - save_cache:
          key: py-deps-{{ checksum "ml_api/requirements.txt" }}
          paths:
            - "/venv"      

  train_and_upload_regression_model:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - run: 
          name: Install requirements
          command: |
            . venv/bin/activate
            pip install -r src/requirements.txt      
      - run:
          name: Train model
          command: |
            . venv/bin/activate
            PYTHONPATH=./src python3 src/regression_model/train_pipeline.py
      - run: 
          name: Publish model to Gemfury
          command: |
            . venv/bin/activate
            chmod +x ./scripts/publish_model.sh
            ./scripts/publish_model.sh ./src/

  section_9_differential_tests:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - run:
          name: Capturing previous model predictions
          command: |
            . venv/bin/activate
            pip install -r ml_api/diff_test_requirements.txt
            PYTHONPATH=./ml_api python3 ml_api/tests/capture_model_predictions.py
      - run:
          name: Runnning differential tests
          command: |
            . venv/bin/activate
            pip install -r ml_api/requirements.txt
            py.test -vv ml_api/tests -m differential

workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
      - test_ml_api
      - differential_tests
      - train_and_upload_regression_model:
          requires:
            - test_regression_model
            - test_ml_api
            - differential_tests
          filters:
            branches:
              only:
                - master
