version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/regression_model/requirements.txt
            py.test -vv packages/regression_model/tests

workflows:
  version: 2.1
  test-all:
    jobs:
      - test_regression_model
